import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <h1 className="text-4xl font-bold">Welcome to T3 App!</h1>
        </Layout>
      </main>
    </>
  );
};

export default Home;
